# Application
spring.application.name=profile

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# H2 Database 
spring.datasource.url=jdbc:h2:./data/profileDb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Initialize
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Email Configuration 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=qaisbutt2004@gmail.com
spring.mail.password=cqtdwdvnrdzqhxca 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=38c9464e6dce9709193d997a3f6a240e5dc5b2f24c99a24d38ba105f64d1714d
jwt.expiration=86400000 # 24 hours in milliseconds



server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
logging.level.com.example.profile=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.settings.web-allow-others=true
