-- Table for User entities (mapped to the User class)
CREATE TABLE IF NOT EXISTS "PROFILES" (
    "ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
    "EMAIL" VARCHAR(255) UNIQUE NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "EMAIL_VERIFIED" BOOLEAN DEFAULT FALSE
);

-- Table for EmailVerificationToken entities
CREATE TABLE IF NOT EXISTS "EmailVerificationToken" (
    "ID" BIGINT PRIMARY KEY AUTO_INCREMENT,
    "TOKEN" VARCHAR(255) UNIQUE NOT NULL,
    "EXPIRES_AT" TIMESTAMP NOT NULL,
    "VERIFIED_AT" TIMESTAMP NULL,
    "PROFILE_ID" BIGINT NOT NULL,
    FOREIGN KEY ("PROFILE_ID") REFERENCES "PROFILES"("ID")
);